name: ReNest
version: 1.0.0+1
publish_to: none
description: A system for helping people move to unfamiliar places.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: ^8.1.3
  json_serializable: ^6.1.3
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.3
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/test_data/tasks.json
  uses-material-design: true
  fonts:
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab-Regular.ttf
          style: normal
        - asset: assets/fonts/ZillaSlab-SemiBoldItalic.ttf
          style: italic
    - family: VTCMartin
      fonts:
        - asset: assets/fonts/VTC-Martin-Regular.ttf
          style: normal
    - family: VangaurdCF
      fonts:
        - asset: assets/fonts/VanguardCF-Bold.otf
    - family: TTInterfaces
      fonts:
        - asset: assets/fonts/TTInterfaces-Regular.ttf
          style: normal
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
          style: normal
    - family: OptimaNovaLT
      fonts:
        - asset: assets/fonts/OptimaNovaLT-Regular.otf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          style: normal
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Italic.ttf
          style: italic
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
          style: normal
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
    - family: Copperplate
      fonts:
        - asset: assets/fonts/copperplate/Copperplate.ttf
        - asset: assets/fonts/copperplate/Copperplate-Bold.ttf
        - asset: assets/fonts/copperplate/Copperplate-Light.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Black.ttf
        - asset: assets/fonts/avenir/Avenir-BlackOblique.ttf
        - asset: assets/fonts/avenir/Avenir-Book.ttf
        - asset: assets/fonts/avenir/Avenir-BookOblique.ttf
        - asset: assets/fonts/avenir/Avenir-Heavy.ttf
        - asset: assets/fonts/avenir/Avenir-HeavyOblique.ttf
        - asset: assets/fonts/avenir/Avenir-Light.ttf
        - asset: assets/fonts/avenir/Avenir-LightOblique.ttf
        - asset: assets/fonts/avenir/Avenir-Medium.ttf
        - asset: assets/fonts/avenir/Avenir-MediumOblique.ttf
        - asset: assets/fonts/avenir/Avenir-Oblique.ttf
        - asset: assets/fonts/avenir/Avenir-Roman.ttf
    - family: AT-Apoc-Dark
      fonts:
        - asset: assets/fonts/AT-Apoc-Dark.otf
          style: normal
        - asset: assets/fonts/AT-Apoc-Dark-Italic.otf
          style: italic




